package ru.ifmo.wst.lab1.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ExterminatusService", targetNamespace = "http://ws.lab1.wst.ifmo.ru/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ExterminatusService {


    /**
     * @return returns java.util.List<ru.ifmo.wst.lab1.ws.ExterminatusEntity>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://ws.lab1.wst.ifmo.ru/", className = "ru.ifmo.wst.lab1.ws.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://ws.lab1.wst.ifmo.ru/", className = "ru.ifmo.wst.lab1.ws.FindAllResponse")
    @Action(input = "http://ws.lab1.wst.ifmo.ru/ExterminatusService/findAllRequest", output = "http://ws.lab1.wst.ifmo.ru/ExterminatusService/findAllResponse", fault = {
            @FaultAction(className = SQLException_Exception.class, value = "http://ws.lab1.wst.ifmo.ru/ExterminatusService/findAll/Fault/SQLException")
    })
    public List<ExterminatusEntity> findAll()
            throws SQLException_Exception
    ;

    /**
     * @param date
     * @param reason
     * @param method
     * @param planet
     * @param initiator
     * @param id
     * @return returns java.util.List<ru.ifmo.wst.lab1.ws.ExterminatusEntity>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "filter", targetNamespace = "http://ws.lab1.wst.ifmo.ru/", className = "ru.ifmo.wst.lab1.ws.Filter")
    @ResponseWrapper(localName = "filterResponse", targetNamespace = "http://ws.lab1.wst.ifmo.ru/", className = "ru.ifmo.wst.lab1.ws.FilterResponse")
    @Action(input = "http://ws.lab1.wst.ifmo.ru/ExterminatusService/filterRequest", output = "http://ws.lab1.wst.ifmo.ru/ExterminatusService/filterResponse", fault = {
            @FaultAction(className = SQLException_Exception.class, value = "http://ws.lab1.wst.ifmo.ru/ExterminatusService/filter/Fault/SQLException")
    })
    public List<ExterminatusEntity> filter(
            @WebParam(name = "id", targetNamespace = "")
                    Long id,
            @WebParam(name = "initiator", targetNamespace = "")
                    String initiator,
            @WebParam(name = "reason", targetNamespace = "")
                    String reason,
            @WebParam(name = "method", targetNamespace = "")
                    String method,
            @WebParam(name = "planet", targetNamespace = "")
                    String planet,
            @WebParam(name = "date", targetNamespace = "")
                    XMLGregorianCalendar date)
            throws SQLException_Exception
    ;

}
