version: '3.5'
services:
  build-app:
    volumes:
      - application:/build
    build: .
  standalone-exterminatus:
    depends_on:
      - postgres
      - build-app
    ports:
      - "9999:8080"
    expose:
      - "8080"
    build:
      dockerfile: Dockerfile-standalone
      context: ./docker-files
    command: >
      sh -c "cp /build/standalone-jaxws/target/standalone-jaxws-1.0-jar-with-dependencies.jar / &&
             /wait-for postgres:5432 -- java -jar /standalone-jaxws-1.0-jar-with-dependencies.jar"
    links:
      - "postgres:postgres"
    volumes:
      - application:/build
  postgres:
    build:
      dockerfile: Dockerfile-data
      context: .
    volumes:
      - exterminatus-data:/var/lib/postgresql/data
  glassfish:
    depends_on:
      - build-app
      - postgres
    build:
      context: .
      dockerfile: Dockerfile-glassfish
    command: wait-for postgres:5432 -- ./start-glassfish.sh
    volumes:
      - application:/build
    ports:
      - "9090:8080"
      - "9191:8181"
      - "9393:4848"
volumes:
  application: {}
  exterminatus-data: {}
