package ru.ifmo.wst.lab1.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ExterminatusServiceService", targetNamespace = "http://ws.lab1.wst.ifmo.ru/", wsdlLocation = "http://localhost:8080/EXTERMINATE?wsdl")
public class ExterminatusServiceService
        extends Service {

    private final static URL EXTERMINATUSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXTERMINATUSSERVICESERVICE_EXCEPTION;
    private final static QName EXTERMINATUSSERVICESERVICE_QNAME = new QName("http://ws.lab1.wst.ifmo.ru/", "ExterminatusServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EXTERMINATE?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXTERMINATUSSERVICESERVICE_WSDL_LOCATION = url;
        EXTERMINATUSSERVICESERVICE_EXCEPTION = e;
    }

    public ExterminatusServiceService() {
        super(__getWsdlLocation(), EXTERMINATUSSERVICESERVICE_QNAME);
    }

    public ExterminatusServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXTERMINATUSSERVICESERVICE_QNAME, features);
    }

    public ExterminatusServiceService(URL wsdlLocation) {
        super(wsdlLocation, EXTERMINATUSSERVICESERVICE_QNAME);
    }

    public ExterminatusServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXTERMINATUSSERVICESERVICE_QNAME, features);
    }

    public ExterminatusServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExterminatusServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (EXTERMINATUSSERVICESERVICE_EXCEPTION != null) {
            throw EXTERMINATUSSERVICESERVICE_EXCEPTION;
        }
        return EXTERMINATUSSERVICESERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns ExterminatusService
     */
    @WebEndpoint(name = "ExterminatusServicePort")
    public ExterminatusService getExterminatusServicePort() {
        return super.getPort(new QName("http://ws.lab1.wst.ifmo.ru/", "ExterminatusServicePort"), ExterminatusService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ExterminatusService
     */
    @WebEndpoint(name = "ExterminatusServicePort")
    public ExterminatusService getExterminatusServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.lab1.wst.ifmo.ru/", "ExterminatusServicePort"), ExterminatusService.class, features);
    }

}
